### ISSUE TITLE
eager option on request object

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-http-driver#14]
Could add a "eager: true" option to the request object which will execute the request even if you are not using its corresponding response.

**Comment by Widdershin** [comment]
As discussed in gitter: [August 24, 2015 7:32 PM](https://gitter.im/cyclejs/cycle-core?at=55dac882fcfd5a7865af0d12)

It might be an idea to default to `eager: true`. It's a bit counter-intuitive to create a request that doesn't fire because you're not subscribed to the result (for beginners at least).

**Comment by staltz** [comment]
@Widdershin https://github.com/cyclejs/cycle-http-driver/releases/tag/v3.1.0 implemented this feature.
